### ISSUE TITLE
More servers 

### ISSUE THREAD

**Issue by shawe** [Free-Software-for-Android/AdAway#520] opened 2014-04-19 11:05 UTC
http://adblock.mahakala.is/friendly

http://adblock.mahakala.is/hybrid

http://adblock.mahakala.is/mahakala

This are the biggests files that I found, but the problem is that your app crash while processing all hosts files I included.

**Comment by 0-kaladin** [comment] 2015-08-29 20:48
duplicate of #626

**Closed by 0-kaladin** 2015-08-29 20:48 UTC
Labels: duplicate
