### ISSUE TITLE
fails to reboot 

### ISSUE THREAD

**Issue by haro25** [Free-Software-for-Android/AdAway#597] opened 2015-02-08 14:45 UTC
Every time I apply new host files and click on reboot now it fails to reboot. Im using samsung galaxy s3 virgin mobile. Its not a big deal cause I have quick boot installed just thought I'd pass on the information

**Comment by 0-kaladin** [comment] 2015-09-10 13:44
Would need a logcat or some debug log to see what is going on.  Since this isn't reported anywhere else and works for me it must be specific to your device.  If we don't get the necessary logs to help troubleshoot, and since it not reproducible locally, I'll close this out after a week or two if we don't hear back since this was created months ago.

**Closed** 2015-09-20 02:24 UTC
Labels: bug
